/**
 * Справочник маппинга латинских слагов в русские названия для хлебных крошек.
 *
 * Приоритет: словарь (SLUG_TO_RUSSIAN_NAME) > fallback-капитализация.
 */

import { CONTINENT_LABELS } from '@/shared/constants/continents';

export interface BreadcrumbItem {
  name: string;
  href: string;
}

const SLUG_TO_RUSSIAN_NAME: Record<string, string> = {
  // Static routes
  '': 'Главная',
  wiki: 'Энциклопедия',
  countries: 'Страны',
  tours: 'Туры',
  cruises: 'Круизы',
  about: 'О нас',
  contacts: 'Контакты',
  privacy: 'Конфиденциальность',
  terms: 'Условия',
  reviews: 'Отзывы',
  intro: 'Введение',
  culture: 'Культура',
  'travel-tips': 'Советы',
  places: 'Места',
  cities: 'Города вылета',
  mission: 'Миссия',
  values: 'Ценности',
  support: 'Поддержка',
  destinations: 'Направления',
  hotels: 'Отели',
  blog: 'Блог',
  faq: 'Частые вопросы',
  partners: 'Партнёры',

  // Blog posts
  'kuda-poehat-v-fevrale-2026': 'Куда поехать в феврале 2026',
  'top-10-oteley-dubaya': 'Топ-10 отелей Дубая',
  'skolko-stoit-tur-v-turciyu-na-dvoih': 'Сколько стоит тур в Турцию на двоих',
  'vizy-v-evropu-dlya-rossiyan-2026': 'Визы в Европу для россиян 2026',
  'kak-vybrat-otel-v-turcii-2026': 'Как выбрать отель в Турции 2026',
  'morskie-kruizy-2026-gid-dlya-nachinayuschih': 'Морские круизы 2026 гид для начинающих',
  'strahovanie-dlya-puteshestviy-2026': 'Страхование для путешествий 2026',
  'kak-sokratit-rashody-na-puteshestvie-2026': 'Как сократить расходы на путешествие 2026',

  // Continents & Regions - импортируем из единого источника
  ...CONTINENT_LABELS,
  america: 'Америка',
  australia: 'Австралия',
  extreme: 'Экстрим',
  cruise: 'Круизные туры',
  mediterranean: 'Средиземноморье',
  caribbean: 'Карибы',
  scandinavian: 'Скандинавия',
  alaska: 'Аляска',
  world: 'Кругосветные',

  // Europe
  albania: 'Албания',
  andorra: 'Андорра',
  armenia: 'Армения',
  austria: 'Австрия',
  belarus: 'Беларусь',
  belgium: 'Бельгия',
  bosnia: 'Босния и Герцеговина',
  bulgaria: 'Болгария',
  croatia: 'Хорватия',
  cyprus: 'Кипр',
  vatican: 'Ватикан',
  uk: 'Великобритания',
  denmark: 'Дания',
  iceland: 'Исландия',
  ireland: 'Ирландия',
  italy: 'Италия',
  spain: 'Испания',
  france: 'Франция',
  germany: 'Германия',
  greece: 'Греция',
  hungary: 'Венгрия',
  latvia: 'Латвия',
  lithuania: 'Литва',
  liechtenstein: 'Лихтенштейн',
  luxembourg: 'Люксембург',
  malta: 'Мальта',
  moldova: 'Молдова',
  monaco: 'Монако',
  netherlands: 'Нидерланды',
  norway: 'Норвегия',
  poland: 'Польша',
  portugal: 'Португалия',
  romania: 'Румыния',
  russia: 'Россия',
  'san-marino': 'Сан-Марино',
  'north-macedonia': 'Северная Македония',
  serbia: 'Сербия',
  slovakia: 'Словакия',
  slovenia: 'Словения',
  ukraine: 'Украина',
  finland: 'Финляндия',
  sweden: 'Швеция',
  montenegro: 'Черногория',
  czechia: 'Чехия',
  switzerland: 'Швейцария',
  estonia: 'Эстония',
  'northern-cyprus': 'Северный Кипр',
  kosovo: 'Косово',
  'south-ossetia': 'Южная Осетия',
  transnistria: 'Приднестровье',
  artsakh: 'Нагорный Карабах',
  donetsk: 'Донецк',
  luhansk: 'Луганск',

  // Asia
  afghanistan: 'Афганистан',
  azerbaijan: 'Азербайджан',
  china: 'Китай',
  india: 'Индия',
  indonesia: 'Индонезия',
  japan: 'Япония',
  kazakhstan: 'Казахстан',
  malaysia: 'Малайзия',
  mongolia: 'Монголия',
  nepal: 'Непал',
  pakistan: 'Пакистан',
  philippines: 'Филиппины',
  singapore: 'Сингапур',
  'south-korea': 'Южная Корея',
  thailand: 'Таиланд',
  turkey: 'Турция',
  uzbekistan: 'Узбекистан',
  vietnam: 'Вьетнам',
  bahrain: 'Бахрейн',
  bangladesh: 'Бангладеш',
  bhutan: 'Бутан',
  brunei: 'Бруней',
  cambodia: 'Камбоджа',
  georgia: 'Грузия',
  iran: 'Иран',
  iraq: 'Ирак',
  israel: 'Израиль',
  jordan: 'Иордания',
  kuwait: 'Кувейт',
  kyrgyzstan: 'Кыргызстан',
  laos: 'Лаос',
  macau: 'Макао',
  maldives: 'Мальдивы',
  maldivy: 'Мальдивы',
  myanmar: 'Мьянма',
  'north-korea': 'Северная Корея',
  oman: 'Оман',
  palestine: 'Палестина',
  qatar: 'Катар',
  'sri-lanka': 'Шри-Ланка',
  syria: 'Сирия',
  taiwan: 'Тайвань',
  tajikistan: 'Таджикистан',
  turkmenistan: 'Туркменистан',
  uae: 'ОАЭ',
  yemen: 'Йемен',
  'hong-kong': 'Гонконг',
  tibet: 'Тибет',
  lebanon: 'Ливан',

  // Africa
  egypt: 'Египет',
  'burkina-faso': 'Буркина-Фасо',
  burundi: 'Бурунди',
  'cabo-verde': 'Кабо-Верде',
  comoros: 'Коморы',
  congo: 'Конго',
  'cote-d-ivoire': 'Кот-д’Ивуар',
  'cote-divoire': 'Кот-д’Ивуар',
  'dr-congo': 'ДР Конго',
  djibouti: 'Джибути',
  'equatorial-guinea': 'Экваториальная Гвинея',
  eritrea: 'Эритрея',
  eswatini: 'Эсватини',
  ethiopia: 'Эфиопия',
  gabon: 'Габон',
  gambia: 'Гамбия',
  ghana: 'Гана',
  guinea: 'Гвинея',
  'guinea-bissau': 'Гвинея-Бисау',
  kenya: 'Кения',
  lesotho: 'Лесото',
  liberia: 'Либерия',
  libya: 'Ливия',
  madagascar: 'Мадагаскар',
  malawi: 'Малави',
  mali: 'Мали',
  mauritania: 'Мавритания',
  mauritius: 'Маврикий',
  mozambique: 'Мозамбик',
  namibia: 'Намибия',
  niger: 'Нигер',
  nigeria: 'Нигерия',
  rwanda: 'Руанда',
  'sao-tome-and-principe': 'Сан-Томе и Принсипи',
  senegal: 'Сенегал',
  seychelles: 'Сейшелы',
  'sierra-leone': 'Сьерра-Леоне',
  somalia: 'Сомали',
  'south-africa': 'ЮАР',
  sudan: 'Судан',
  tanzania: 'Танзания',
  togo: 'Того',
  tunisia: 'Тунис',
  uganda: 'Уганда',
  zambia: 'Замбия',
  zimbabwe: 'Зимбабве',
  'western-sahara': 'Западная Сахара',
  'sahrawi-arab-democratic-republic': 'САДР',
  somaliland: 'Сомалиленд',
  botswana: 'Ботсвана',
  benin: 'Бенин',
  angola: 'Ангола',
  algeria: 'Алжир',
  cameroon: 'Камерун',
  'central-african-republic': 'ЦАР',
  chad: 'Чад',
  morocco: 'Марокко',
  'south-sudan': 'Южный Судан',
  reunion: 'Реюньон',
  'saint-helena': 'Остров Святой Елены',

  // North America
  'antigua-barbuda': 'Антигуа и Барбуда',
  bahamas: 'Багамы',
  barbados: 'Барбадос',
  belize: 'Белиз',
  canada: 'Канада',
  'costa-rica': 'Коста-Рика',
  cuba: 'Куба',
  dominica: 'Доминика',
  'dominican-republic': 'Доминикана',
  'el-salvador': 'Сальвадор',
  grenada: 'Гренада',
  guatemala: 'Гватемала',
  haiti: 'Гаити',
  honduras: 'Гондурас',
  jamaica: 'Ямайка',
  mexico: 'Мексика',
  nicaragua: 'Никарагуа',
  panama: 'Панама',
  'saint-kitts-and-nevis': 'Сент-Китс и Невис',
  'saint-lucia': 'Сент-Люсия',
  'saint-vincent-and-the-grenadines': 'Сент-Винсент и Гренадины',
  'trinidad-and-tobago': 'Тринидад и Тобаго',
  usa: 'США',
  'puerto-rico': 'Пуэрто-Рико',
  'saint-martin': 'Сен-Мартен',
  'saint-barthelemy': 'Сен-Бартелеми',
  'saint-pierre-and-miquelon': 'Сен-Пьер и Микелон',

  // South America
  argentina: 'Аргентина',
  bolivia: 'Боливия',
  brazil: 'Бразилия',
  chile: 'Чили',
  colombia: 'Колумбия',
  ecuador: 'Эквадор',
  guyana: 'Гайана',
  paraguay: 'Парагвай',
  peru: 'Перу',
  suriname: 'Суринам',
  uruguay: 'Уругвай',
  venezuela: 'Венесуэла',

  // Oceania
  fiji: 'Фиджи',
  kiribati: 'Кирибати',
  'marshall-islands': 'Маршалловы Острова',
  micronesia: 'Микронезия',
  nauru: 'Науру',
  'new-zealand': 'Новая Зеландия',
  palau: 'Палау',
  'papua-new-guinea': 'Папуа — Новая Гвинея',
  samoa: 'Самоа',
  'solomon-islands': 'Соломоновы Острова',
  tonga: 'Тонга',
  tuvalu: 'Тувалу',
  vanuatu: 'Вануату',
  niue: 'Ниуэ',
  'northern-mariana-islands': 'Северные Марианские Острова',

  // Cities & Regions (most frequently used)
  moscow: 'Москва',
  'sankt-peterburg': 'Санкт-Петербург',
  'novosibirsk': 'Новосибирск',
  'ekaterinburg': 'Екатеринбург',
  kazan: 'Казань',
  'nizhny-novgorod': 'Нижний Новгород',
  krasnoyarsk: 'Красноярск',
  chelyabinsk: 'Челябинск',
  samara: 'Самара',
  ufa: 'Уфа',
  'rostov-on-don': 'Ростов-на-Дону',
  krasnodar: 'Краснодар',
  omsk: 'Омск',
  voronezh: 'Воронеж',
  perm: 'Пермь',
  volgograd: 'Волгоград',
  saratov: 'Саратов',
  tyumen: 'Тюмень',
  irkutsk: 'Иркутск',
  barnaul: 'Барнаул',
  'ulyanovsk': 'Ульяновск',
  vladivostok: 'Владивосток',
  yaroslavl: 'Ярославль',
  'yoshkar-ola': 'Йошкар-Ола',
  khabarovsk: 'Хабаровск',
  makhachkala: 'Махачкала',
  tomsk: 'Томск',
  orenburg: 'Оренбург',
  kemerovo: 'Кемерово',
  'novorossiysk': 'Новороссийск',
  astrakhan: 'Астрахань',
  penza: 'Пенза',
  lipetsk: 'Липецк',
  kirov: 'Киров',
  cheboksary: 'Чебоксары',
  kaliningrad: 'Калининград',
  tver: 'Тверь',
  sochi: 'Сочи',
  stavropol: 'Ставрополь',
  ulanude: 'Улан-Удэ',
  'magnitogorsk': 'Магнитогорск',
  vladikavkaz: 'Владикавказ',
  surgut: 'Сургут',
  vologda: 'Вологда',
  simferopol: 'Симферополь',
  belgorod: 'Белгород',
  'novokuznetsk': 'Новокузнецк',
  yakutsk: 'Якутск',
  bryansk: 'Брянск',
  kostroma: 'Кострома',
  orsk: 'Орск',
  bratsk: 'Братск',
  'nizhnevartovsk': 'Нижневартовск',
  shakhty: 'Шахты',
  seversk: 'Северск',
  engels: 'Энгельс',
  armavir: 'Армавир',
  korolyov: 'Королёв',
  krasnogorsk: 'Красногорск',
  khimki: 'Химки',
  balashikha: 'Балашиха',
  'podolsk': 'Подольск',
  muzhi: 'Мужи',
  kogalym: 'Когалым',
  nizhnekamsk: 'Нижнекамск',
  'anadyr': 'Анадырь',
  petrozavodsk: 'Петрозаводск',
  murmansk: 'Мурманск',
  syktyvkar: 'Сыктывкар',
  abakan: 'Абакан',
  sebastopol: 'Севастополь',
  'veliky-novgorod': 'Великий Новгород',
  vladimir: 'Владимир',
  yoshkar: 'Йошкар-Ола',
  ivanovo: 'Иваново',
  kaluga: 'Калуга',
  'nizhny': 'Нижний Новгород',

  // Federal subjects / Republics (optimized slugs)
  'respublika-marii-el': 'Республика Марий Эл',
  'mari-el': 'Республика Марий Эл',
  'respublika-saha': 'Республика Саха (Якутия)',
  'saha-yakutiya': 'Республика Саха (Якутия)',
  'krasnoyarsk-kray': 'Красноярский край',
  'krasnodar-kray': 'Краснодарский край',
  'stavropol-kray': 'Ставропольский край',
  'permsky-kray': 'Пермский край',
  'habarovsky-kray': 'Хабаровский край',
  'primorsky-kray': 'Приморский край',
  'moskovskaya-oblast': 'Московская область',
  'leningradskaya-oblast': 'Ленинградская область',
  crimea: 'Крым',
  'respublika-krym': 'Республика Крым',
  zaporozhye: 'Запорожье',
  kherson: 'Херсон',
  'respublika-tatarstan': 'Республика Татарстан',
  bashkortostan: 'Республика Башкортостан',
  dagestan: 'Республика Дагестан',
  ingushetia: 'Республика Ингушетия',
  chechnya: 'Чеченская Республика',
  'kabardino-balkariya': 'Кабардино-Балкария',
  'karachay-cherkessiya': 'Карачаево-Черкесия',
  'north-osetia': 'Северная Осетия',
  adygeya: 'Республика Адыгея',
  kalmykiya: 'Республика Калмыкия',
  altay: 'Республика Алтай',
  tyva: 'Республика Тыва (Тува)',
  hakasiya: 'Республика Хакасия',
  buryatiya: 'Республика Бурятия',
  kareliya: 'Республика Карелия',
  komi: 'Республика Коми',
  udmurtiya: 'Удмуртская Республика',
  'mariy-el': 'Республика Марий Эл',
  'chuvashiya': 'Чувашская Республика',
  'mordoviya': 'Республика Мордовия',
  'zabaykalsky-kray': 'Забайкальский край',
  'kamchatka-kray': 'Камчатский край',
  'amurskaya-oblast': 'Амурская область',
  'volgogradskaya-oblast': 'Волгоградская область',
  'vologodskaya-oblast': 'Вологодская область',
  'voronezhskaya-oblast': 'Воронежская область',
  'ivanovskaya-oblast': 'Ивановская область',
  'irkutskaya-oblast': 'Иркутская область',
  'kaluzhskaya-oblast': 'Калужская область',
  'kemerovskaya-oblast': 'Кемеровская область',
  'kirovskaya-oblast': 'Кировская область',
  'kostromskaya-oblast': 'Костромская область',
  'kurganskaya-oblast': 'Курганская область',
  'kurskaya-oblast': 'Курская область',
  'lipetskaya-oblast': 'Липецкая область',
  'magadanskaya-oblast': 'Магаданская область',
  'murmanskaya-oblast': 'Мурманская область',
  'nizhegorodskaya-oblast': 'Нижегородская область',
  'novgorodskaya-oblast': 'Новгородская область',
  'novosibirskaya-oblast': 'Новосибирская область',
  'omskaya-oblast': 'Омская область',
  'orenburgskaya-oblast': 'Оренбургская область',
  'orlovskaya-oblast': 'Орловская область',
  'penzenskaya-oblast': 'Пензенская область',
  'permskiy-kray': 'Пермский край',
  'pskovskaya-oblast': 'Псковская область',
  'rostovskaya-oblast': 'Ростовская область',
  'ryazanskaya-oblast': 'Рязанская область',
  'sakhalinskaya-oblast': 'Сахалинская область',
  'sakhalin': 'Сахалинская область',
  'samarskaya-oblast': 'Самарская область',
  'saratovskaya-oblast': 'Саратовская область',
  'smolenskaya-oblast': 'Смоленская область',
  'sverdlovskaya-oblast': 'Свердловская область',
  'tambovskaya-oblast': 'Тамбовская область',
  'tverskaya-oblast': 'Тверская область',
  'tomskaya-oblast': 'Томская область',
  'tulskaya-oblast': 'Тульская область',
  'tyumenskaya-oblast': 'Тюменская область',
  'ulyanovskaya-oblast': 'Ульяновская область',
  'chelyabinskaya-oblast': 'Челябинская область',
  'yaroslavskaya-oblast': 'Ярославская область',
};

/**
 * Возвращает русское название по латинскому слагу и типу сущности.
 * Приоритет: словарь > красивый фолбэк.
 */
export function getRussianNameBySlug(slug: string, type: 'city' | 'region' | 'country' = 'city'): string {
  const normalized = slug.toLowerCase().trim();

  if (SLUG_TO_RUSSIAN_NAME[normalized]) {
    return SLUG_TO_RUSSIAN_NAME[normalized];
  }

  const fallback = normalized
    .replace(/[-\s]+/g, ' ')
    .split(' ')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  if (type === 'region' || type === 'country') {
    return fallback;
  }

  return fallback;
}
